version: '3.1'

services:
# DS4VO1)t5TCE@bCpBv
  wordpress:
    image: wordpress-custom
    build: wordpress
    restart: always
    ports:
      - 8080:8080
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DEBUG: true
    volumes:
      - wordpress:/var/www/html
      - c:/tmp/wordpress/wp-config.php:/var/www/html/wp-config.php
      - c:/tmp/wordpress/plugin.php:/var/www/html/wp-content/plugins/configure-openid/plugin.php

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
